"""
============================================================
MIGRATION: create_events_table
============================================================

CONCEITO — Migration (Alembic):
  Uma migration é um script versionado que altera o
  esquema do banco de dados de forma controlada.

  Cada migration tem:
    - upgrade(): aplica a mudança (avança versão)
    - downgrade(): reverte a mudança (volta versão)

COMANDOS ÚTEIS:
  Aplicar todas as migrations pendentes:
    alembic upgrade head

  Voltar uma versão:
    alembic downgrade -1

  Ver histórico:
    alembic history

  Ver versão atual do banco:
    alembic current

Revision ID: 562c2c6193ba
Revises:
Create Date: 2026-03-10 14:17:01.453036
============================================================
"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562c2c6193ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sa.Enum('CONGRESS', 'SEMINAR', 'WORKSHOP', 'LECTURE', 'SHORT_COURSE', 'SYMPOSIUM', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organizer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_start_date'), 'events', ['start_date'], unique=False)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_start_date'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
