# Generated by Django 6.0.5 on 2026-05-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=200)),
                ('tecnico', models.CharField(max_length=200)),
                ('grupo_fase1', models.CharField(choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D'), ('E', 'Grupo E'), ('F', 'Grupo F'), ('G', 'Grupo G')])),
            ],
        ),
    ]
