###

@baseURL = http://localhost:8000
# @baseURL = https://api-fifa-386.onrender.com

GET {{baseURL}}/api/selecoes


###
GET {{baseURL}}/api/selecoes/2


###
POST {{baseURL}}/api/selecoes/ HTTP/1.1
Content-Type: application/json

{
    "tecnico": "Joaquim",
    "pais": "Portugal",
    "grupo_fase1": "G"
}

###
GET {{baseURL}}/api/sedes

###
GET {{baseURL}}/api/sedes/1


###
DELETE {{baseURL}}/api/sedes/1


###
POST {{baseURL}}/api/sedes HTTP/1.1
Content-Type: application/json

{
    "cidade": "Teresina",
    "estadio": "Big Albert Stadium"
}

###

PUT {{baseURL}}/api/sedes/1 HTTP/1.1
Content-Type: application/json

{
    "cidade": "Timon",
    "estadio": "TStadium"
}